#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Update project documentation
npm run update-docs

# Stage the updated documentation if it was changed
git diff --quiet .notes/project-guide.md || git add .notes/project-guide.md